version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nomads
    container_name: nomads
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - nomads-network

  db:
    image: mysql:5.7
    container_name: nomads-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - nomads-network

  nginx:
    image: nginx:alpine
    container_name: nomads-nginx
    restart: unless-stopped
    ports:
      - 7000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - nomads-network

networks:
  nomads-network:
    driver: bridge